const Language = [
    "English",
    "Spanish",
    "French",
    "German",
    "Japanese",
    "Italian",
    "Korean",
    "Mandarin Chinese",
    "Russian",
    "Brazilian Portuguese",
    "Arabic",
    "Turkish",
    "Dutch",
    "Swedish",
    "Hindi",
    "Greek",
    "Irish",
    "Polish",
    "Latin",
    "Norwegian Bokmål",
    "Hebrew",
    "High Valyrian",
    "Vietnamese",
    "Hawaiian",
    "Danish",
    "Romanian",
    "Czech",
    "Welsh",
    "Indonesian",
    "Swahili",
    "Ukrainian",
    "Esperanto",
    "Scottish Gaelic",
];

export default Language;